columns:
  - hotel: object
  - is_canceled: int64
  - lead_time: int64
  - arrival_date_year: int64
  - arrival_date_month: object
  - arrival_date_week_number: int64
  - arrival_date_day_of_month: int64
  - stays_in_weekend_nights: int64
  - stays_in_week_nights: int64
  - adults: int64
  - children: float64
  - babies: int64
  - meal: object
  - country: object
  - market_segment: object
  - distribution_channel: object
  - is_repeated_guest: int64
  - previous_cancellations: int64
  - previous_bookings_not_canceled: int64
  - reserved_room_type: object
  - assigned_room_type: object
  - booking_changes: int64
  - deposit_type: object
  - agent: float64
  - company: float64
  - days_in_waiting_list: int64
  - customer_type: object
  - adr: float64
  - required_car_parking_spaces: int64
  - total_of_special_requests: int64
  - reservation_status: object
  - reservation_status_date: object


categorical_columns:
  - meal
  - country
  - market_segment
  - distribution_channel
  - reserved_room_type
  - assigned_room_type
  - deposit_type
  - customer_type

numerical_columns:
  - lead_time
  - arrival_date_week_number
  - stays_in_weekend_nights
  - stays_in_week_nights
  - adults
  - children
  - babies
  - is_repeated_guest
  - previous_cancellations
  - previous_bookings_not_canceled
  - booking_changes
  - days_in_waiting_list
  - adr
  - required_car_parking_spaces
  - total_of_special_requests


transform_columns:
  - 'arrival_date_month'
  - 'assigned_room_type'
  - 'reserved_room_type'
  - 'arrival_date_day_of_month'


drop_columns:
  - hotel
  - reservation_status
  - reservation_status_date
  - arrival_date_year
  - agent
  - company
  - arrival_date_day_of_month
  - arrival_date_month

or_columns:
  - customer_type
  - market_segment
  - reserved_room_type
  - distribution_channel
  - assigned_room_type

oh_columns:
  - meal
  - country
  - deposit_type



